### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by lambdalisue** [lambdalisue/fila.vim#1]

**Comment by lambdalisue** [comment]
### Project drawer
<img width="1065" alt="alacritty 2018-11-20 02-58-35" src="https://user-images.githubusercontent.com/546312/48725677-40a75300-ec70-11e8-9577-23cd841ca137.png">

### Split window
<img width="1065" alt="alacritty 2018-11-20 02-59-29" src="https://user-images.githubusercontent.com/546312/48725703-4e5cd880-ec70-11e8-9376-3d25c1a4fc0b.png">

**Comment by lambdalisue** [comment]
![Alacritty 2020-01-27 01-02-52](https://user-images.githubusercontent.com/546312/73137975-11287d80-40a1-11ea-91eb-c75c71aa420e.png)

**Comment by lambdalisue** [comment]
![Alacritty 2020-01-27 01-08-06](https://user-images.githubusercontent.com/546312/73138033-81370380-40a1-11ea-9054-73ccee248910.png)

**Comment by lambdalisue** [comment]
![Kapture 2020-01-27 at 23 25 05](https://user-images.githubusercontent.com/546312/73182684-d552ee00-415c-11ea-88c3-dcb6efcad12d.gif)

**Comment by lambdalisue** [comment]
![Alacritty 2020-01-27 23-36-26](https://user-images.githubusercontent.com/546312/73183241-d89aa980-415d-11ea-876f-30bd4d80f0cd.png)

![Alacritty 2020-01-27 23-37-01](https://user-images.githubusercontent.com/546312/73183310-f10ac400-415d-11ea-80c8-af1609294889.png)

**Comment by lambdalisue** [comment]
![Kapture 2020-01-27 at 23 38 02](https://user-images.githubusercontent.com/546312/73183457-29120700-415e-11ea-8d04-cb959659e369.gif)

**Comment by lambdalisue** [comment]
![Kapture 2020-01-27 at 23 45 18](https://user-images.githubusercontent.com/546312/73184080-324fa380-415f-11ea-8280-e0b6c7a9989f.gif)

**Comment by lambdalisue** [comment]
![Kapture 2020-01-27 at 23 49 53](https://user-images.githubusercontent.com/546312/73184453-c91c6000-415f-11ea-8e6b-f1df4b9284de.gif)

**Comment by lambdalisue** [comment]
![Kapture 2020-01-27 at 23 53 57](https://user-images.githubusercontent.com/546312/73184814-5d86c280-4160-11ea-9ed1-d5a8d66d1774.gif)

**Comment by lambdalisue** [comment]
![Kapture 2020-02-02 at 17 53 39](https://user-images.githubusercontent.com/546312/73605707-090e9780-45e5-11ea-864a-457dd785f1c4.gif)

**Comment by lambdalisue** [comment]
![tmux 2020-08-04 03-56-29](https://user-images.githubusercontent.com/546312/89217137-9e2b3100-d606-11ea-872f-f6c9dcbe2c93.png)

**Comment by lambdalisue** [comment]
![Kapture 2020-08-12 at 9 06 15](https://user-images.githubusercontent.com/546312/89960875-1afb8200-dc7b-11ea-91ed-522a9f1d20df.gif)

**Comment by lambdalisue** [comment]
![Alacritty 2020-08-20 14-07-00](https://user-images.githubusercontent.com/546312/90719223-cdbc8780-e2ee-11ea-8a6e-ea837a194ffa.png)
![Alacritty 2020-08-20 14-08-04](https://user-images.githubusercontent.com/546312/90719227-ceedb480-e2ee-11ea-98c5-0b7cbcb1bb6a.png)

**Comment by lambdalisue** [comment]
![Alacritty 2020-08-20 14-24-23](https://user-images.githubusercontent.com/546312/90720134-f3e32700-e2f0-11ea-82f7-c86512ad5854.png)

**Comment by nickjj** [comment]
This isn't quite a screenshot but I recorded a screencast about Fern the other day at https://www.youtube.com/watch?v=oFc2kr734rs.

Not sure if it has a place in the wiki, but feel free to link to it anywhere you see fit.

**Comment by lambdalisue** [comment]
@nickjj Fantastic! Thanks for that. I've put it on Wiki (https://github.com/lambdalisue/fern.vim/wiki/Links)

**Comment by lambdalisue** [comment]
![tmux 2020-09-06 14-18-59](https://user-images.githubusercontent.com/546312/92318773-f1a5eb80-efc5-11ea-8e39-e2d4d7dba260.png)

**Comment by lambdalisue** [comment]
![fern-bookmark vim: 🌿 fern vim plugin which add bookmark scheme 2020-09-26 23-55-17](https://user-images.githubusercontent.com/546312/94343538-d160ce00-0053-11eb-9ec6-0dd2a4c3f4b0.png)
