### ISSUE TITLE
 I like your plug-in very much

### ISSUE THREAD

**Issue by huayue369** [lambdalisue/fila.vim#14]
I'm a novice at vim. I like your plug-in very much. It's lightweight, fast and powerful compared to nerdtree. But can you add exit commands, such as nerdtree, which starts the first time and exits the second time? I believe this experience will be better! I think justinmk / vim-dirvish plug-in has some good functions, such as K output file details, can you learn from it? Sorry, my English is not very good.

**Comment by lambdalisue** [comment]
Thanks.

1. I think you are talking about the behavior of `:Fila -drawer -toggle`
2. I think you are talking about something like `echo` action.

**Comment by huayue369** [comment]
1 I think you are talking about the behavior of :Fila -drawer -toggle   **yes**
<img width="597" alt="屏幕快照 2019-03-29 下午4 27 32" src="https://user-images.githubusercontent.com/32536764/55219413-d024ca00-523f-11e9-91c8-22b73a85b086.png">
 sorry ! English is poor

**Comment by lambdalisue** [comment]
Is your problem solved?
