### ISSUE TITLE
Open drawer and jump to current file

### ISSUE THREAD

**Issue by obxhdx** [lambdalisue/fila.vim#17]
Let me start by thanking you for this. I've been looking for a faster and more lightweight alternative to NERDTree for a while now and I'm very glad that I found your plugin. It seems to be able to combine everything I liked from existing file explorers out there.

Now, I’m looking for something similar to [NERDTree’s `NERDTreeFind` command](https://github.com/scrooloose/nerdtree/blob/master/doc/NERDTree.txt#L151). I’d really appreciate if you could add this functionality as well. That’s one of my main usages currently with NERDTree (quickly see where a file is located within the dir hierarchy and which other files are its siblings).

It would be also great if you added some documentation as well. So far I was able to understand a lot from reading the code (e.g.: available actions, how to override mappings), but documentation definitely helps.

**Comment by lambdalisue** [comment]
I'm not sure but it sounds like `:Fila . -drawer -reveal=%` is what you want.

> It would be also great if you added some documentation as well. So far I was able to understand a lot from reading the code (e.g.: available actions, how to override mappings), but documentation definitely helps.

Sorry for that. While I'm not really satisfied with the current implementation (that's why I said it's alpha stage), I'd like to change things before writing documentation. Writing english documentation is a bit tough work for me.

**Comment by obxhdx** [comment]
Amazing, `-reveal` is exactly what I was looking for, thank you!

> Sorry for that. While I'm not really satisfied with the current implementation (that's why I said it's alpha stage), I'd like to change things before writing documentation. Writing english documentation is a bit tough work for me.

No worries, I completely understand. And your English is totally fine to me. ;)
